ci:
  skip:
    - prettier
    - eslint
repos:
  - repo: https://github.com/jvllmr/pre-commit-prettier
    rev: v3.7.4
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@latest
          - prettier-plugin-organize-imports@latest
  - repo: local
    hooks:
      - id: eslint
        name: Lint with eslint
        pass_filenames: false
        language: system
        entry: pnpm lint
