ci:
  skip:
    - prettier
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@latest
          - prettier-plugin-organize-imports@latest
